name: Trigger Workflow B

on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'Input 1'
        required: true
      input2:
        description: 'Input 2'
        required: true

jobs:
  trigger-workflow-b:
    runs-on: ubuntu-latest
    
    steps:
    - name: Prepare JSON payload
      id: prepare-payload
      run: |
        #echo "{\"input1\": \"${{ github.event.inputs.input1 }}\", \"input2\": \"${{ github.event.inputs.input2 }}\"}" > payload.json
        echo "Hello ....."
      
    - name: Trigger Workflow B
      uses: peter-evans/repository-dispatch@v2.1.1
      with:
        token: ${{ secrets.GH_TOKEN }}
        event-type: workflow-b-event
#         client-payload: ${{ steps.prepare-payload.outputs.payload }}
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "input1": "${{ github.event.inputs.input1 }}", "test": "test message"}'
