name: Trigger Workflow B

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'User input for Workflow A'
        required: true

jobs:
  trigger-workflow-b:
    runs-on: ubuntu-latest
    
    steps:
    - name: Prepare JSON payload
      id: prepare-payload
      run: |
        echo "{\"input\": \"${{ github.event.inputs.user_input }}\"}" > payload.json
      
    - name: Trigger Workflow B
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/<workflow-b-id>/dispatches \
          -d @payload.json
