name: Trigger Workflow B

on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'STELabel'
        required: true
      input2:
        description: 'DUTVersion'
        required: true
      input3:
        description: 'optionalParams'
        required: false

jobs:
  trigger-workflow-b:
    runs-on: ubuntu-latest
    
    steps:
    - name: Prepare JSON payload
      id: prepare-payload
      run: |
        #echo "{\"input1\": \"${{ github.event.inputs.input1 }}\", \"input2\": \"${{ github.event.inputs.input2 }}\"}" > payload.json
        echo "Hello ....."
      
    - name: Trigger Workflow B
      id: trigger-b
      uses: peter-evans/repository-dispatch@v2.1.1
      with:
        token: ${{ secrets.GH_TOKEN }}
        event-type: workflow-b-event
#         client-payload: ${{ steps.prepare-payload.outputs.payload }}
#         client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "STELabel": "${{ github.event.inputs.input1 }}", "DUTVersion": "${{ github.event.inputs.input2 }}" }'
        client-payload: '{"STELabel": "${{ github.event.inputs.input1 }}", "DUTVersion": "${{ github.event.inputs.input2 }}", "optionalParams": ${{ github.event.inputs.input3 }} }'
        
    # Add this to WorkflowA.yml after the 'Trigger WorkflowB' step
#     - name: Wait and check the status of WorkflowB
#       uses: fountainhead/action-wait-for-commit-status@v1.0.0
#       id: check_status
#       with:
#         github_token: ${{ secrets.GH_TOKEN }}
#         workflow_name: workflow-b.yml
#         owner: context.repo.owner
#         repo: context.repo.repo
#         ref: ${{ github.ref }}
#         interval_seconds: 10
        
    - name: Dispatch an action and get the run ID
      uses: codex-/return-dispatch@v1
      id: return_dispatch
      with:
        token: ${{ secrets.GH_TOKEN }} # Note this is NOT GITHUB_TOKEN but a PAT
        ref:  ${{ github.ref }}
        repo: context.repo.repo
        owner: context.repo.owner
        workflow: workflow-b.yml
        workflow_timeout_seconds: 120 # Default: 300
