name: Trigger Workflow B

on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'STELabel'
        required: true
      input2:
        description: 'DUTVersion'
        required: true
      input3:
        description: 'optionalParams'
        required: false

jobs:
  trigger-workflow-b:
    runs-on: ubuntu-latest
    
    steps:
    - name: Prepare JSON payload
      id: prepare-payload
      run: |
        #echo "{\"input1\": \"${{ github.event.inputs.input1 }}\", \"input2\": \"${{ github.event.inputs.input2 }}\"}" > payload.json
        echo "Hello ....."
      
    - name: Trigger Workflow B
      id: trigger-b
      uses: peter-evans/repository-dispatch@v2.1.1
      with:
        token: ${{ secrets.GH_TOKEN }}
        event-type: workflow-b-event
#         client-payload: ${{ steps.prepare-payload.outputs.payload }}
#         client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "STELabel": "${{ github.event.inputs.input1 }}", "DUTVersion": "${{ github.event.inputs.input2 }}" }'
        client-payload: '{"STELabel": "${{ github.event.inputs.input1 }}", "DUTVersion": "${{ github.event.inputs.input2 }}", "optionalParams": ${{ github.event.inputs.input3 }} }'
        
    # Add this to WorkflowA.yml after the 'Trigger WorkflowB' step
    - name: Wait and check the status of WorkflowB
      uses: dawidd6/action-checkout@v3
      id: check_status
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        workflow_name: workflow-b.yml
        owner: context.repo.owner
        repo: context.repo.repo
        ref: ${{ github.sha }}
        interval_seconds: 10
